export const ANSI = {
    FG: {
        Black: `\x1b[30m`,
        Red: `\x1b[31m`,
        Green: `\x1b[32m`,
        Yellow: `\x1b[33m`,
        Blue: `\x1b[34m`,
        Magenta: `\x1b[35m`,
        Cyan: `\x1b[36m`,
        BrightBlack: `\x1b[90m`,
        BrightRed: `\x1b[91m`,
        BrightGreen: `\x1b[92m`,
        BrightYellow: `\x1b[93m`,
        BrightBlue: `\x1b[94m`,
        BrightMagenta: `\x1b[95m`,
        BrightCyan: `\x1b[96m`,
        White: `\x1b[37m`,
        BrightWhite: `\x1b[97m`,
        RGB: (r: number, g: number, b: number) => `\x1b[38;2;${r};${g};${b}m`,
        256: (n: number) => `\x1b[38;5;${n}m`,
        Default: `\x1b[39m`,
        },
    BG: {
        Black: `\x1b[40m`,
        Red: `\x1b[41m`,
        Green: `\x1b[42m`,
        Yellow: `\x1b[43m`,
        Blue: `\x1b[44m`,
        Magenta: `\x1b[45m`,
        Cyan: `\x1b[46m`,
        White: `\x1b[47m`,
        BrightBlack: `\x1b[100m`,
        BrightRed: `\x1b[101m`,
        BrightGreen: `\x1b[102m`,
        BrightYellow: `\x1b[103m`,
        BrightBlue: `\x1b[104m`,
        BrightMagenta: `\x1b[105m`,
        BrightCyan: `\x1b[106m`,
        BrightWhite: `\x1b[107m`,
        RGB: (r: number, g: number, b: number) => `\x1b[48;2;${r};${g};${b}m`,
        256: (n: number) => `\x1b[48;5;${n}m`,
        Default: `\x1b[49m`,
    },
    STYLE: {
        reset: `\x1b[0m`,
        bold: `\x1b[1m`,
        dim: `\x1b[2m`,
        italic: `\x1b[3m`,
        underline: `\x1b[4m`,
        blink: `\x1b[5m`,
        inverse: `\x1b[7m`,
        hidden: `\x1b[8m`,
        strikethrough: `\x1b[9m`,
        normal: `\x1b[22m`,
        noItalic: `\x1b[23m`,
        noUnderline: `\x1b[24m`,
        noInverse: `\x1b[27m`,
        noHidden: `\x1b[28m`,
        noStrikethrough: `\x1b[29m`,
    },
} as const;

export default { ANSI };